### ISSUE TITLE
Video stream is blocked

### ISSUE THREAD

**Issue by PaimonWheeWhee** [Dovakiin0/animeworldz#17]
## Expected Behavior
The episode should load from GogoAnime.

## Actual Behavior
GogoAnime pulls some weird error and doesn't display the stream

## Steps to Reproduce the Problem

  1. Open the site
  1. Click on a random anime
  1. Scroll down to the GogoAnime embed
![image](https://user-images.githubusercontent.com/81248955/142804465-cb24573d-cf43-44d0-b26b-9e97d28e16a8.png)

**Comment by Dovakiin0** [comment]
Hello @PaimonWheeWhee, thanks for mentioning this issue. It's true that this has been an issue for a while and i am actively working on it.

**Comment by Dovakiin0** [comment]
Currently fixed for now, at the cost of popup ads sometimes, ill be either finding a way to remove ads or change the source completely. Thank you for reaching out
