### ISSUE TITLE
website no longer hosting

### ISSUE THREAD

**Issue by Rage3gamer** [Dovakiin0/animeworldz#28]
heroku no longer hosts animeworldz, if it has been moved, can you give me the link pls?

**Comment by Rage3gamer** [comment]
discord link is also invalid

**Comment by Dovakiin0** [comment]
Hello @Rage3gamer, Heroku has just removed any free plans hosting, which took down animeworldz too. For the moment, it is currently hosted  [here](https://animeworldz.onrender.com). The site may be a little slow to start up on the first load.
