### ISSUE TITLE
show episodes list in watch episode page

### ISSUE THREAD

**Issue by Dovakiin0** [Dovakiin0/animeworldz#5]
episodes needs to be shown together with episode streaming page in order to minimize user effort to change to respective episode. Episodes list are inside AnimeInfo page, which needs to be combined together with WatchEpisode Page.
see demo on the [site](https://animeworldz.herokuapp.com), to see how it is currently

**Comment by kumar4790** [comment]
Hi, do you want to show respective episodes in same format as AnimeInfo page? or what to show with screens on respective episodes? 

Anyways if you want you can assign me.

**Comment by Dovakiin0** [comment]
Sure :+1:, i can assign it to you,
using the watchEpisode page as a component and putting in the AnimeInfo page is what i am thinking here, But if you think of any other good idea feel free to modify it.

ps: for basic info (you may have already looked at it),
the pages are located inside client/src/pages

**Comment by kumar4790** [comment]
Sure Thanks...!

**Comment by kumar4790** [comment]
Hi, I have raised pull request. Please review and merge if it is fine

**Comment by Dovakiin0** [comment]
hello, thank you for the hard work. I'll review and merge in a bit

**Comment by kumar4790** [comment]
Sure.... Please confirm once done

**Comment by Dovakiin0** [comment]
@kumar4790 good work :+1:
